[source]
git = "https://github.com/pop-os/icon-theme.git"
rev = "1a575a8e99b4ae629b9b16543a3a04d148632ba9"
shallow_clone = true

[build]
template = "meson"

[[optional-packages]]
name = "cursors"
files = [
    "usr/share/icons/Pop/cursors**",
    "usr/share/icons/Pop/cursor.theme",
]
