[source]
git = "https://github.com/Gh0s777tt/eos-orbdata.git"
branch = "master"
rev = "bda3e430941b07cc278927aa553bf54e67ca669a"

[build]
template = "custom"
script = """
cp -rv "${COOKBOOK_SOURCE}/"* "${COOKBOOK_STAGE}/"
"""
