[source]
git = "https://github.com/Gh0s777tt/eos-orbdata.git"
branch = "master"
rev = "27131a5326b44b193530a3ce1f75ac1c13c2ddaa"

[build]
template = "custom"
script = """
cp -rv "${COOKBOOK_SOURCE}/"* "${COOKBOOK_STAGE}/"
"""
