[source]
# E-OS vendored mirror of redox-os/pkgar (edit freely; sync via scripts/sync-forks.sh).
git = "https://gitlab.com/e-os/eos-pkgar.git"
branch = "master"
rev = "78e644ad5fa8d5eddfc15fed71ea3e93fea71b5e"

[build]
template = "cargo"
cargopackages = [
    "pkgar",
    "pkgar-keys",
]
cargoflags = [
    "--features cli"
]
