[source]
# E-OS: `eos login:` console prompt. Rebased onto current redox-os/userutils mainline (July).
git = "https://gitlab.com/e-os/eos-userutils.git"
branch = "eos-july"
rev = "28c6923a798339a696af21641b4fce2455aa12a9"

[build]
template = "custom"
script = """
DYNAMIC_INIT
cookbook_cargo
cp -rv "${COOKBOOK_SOURCE}/res" "${COOKBOOK_STAGE}/etc"
ln -s id "${COOKBOOK_STAGE}/usr/bin/whoami"
"""
