[source]
# E-OS: `eos login:` console prompt. Rebased onto current redox-os/userutils mainline (July).
git = "https://gitlab.com/e-os/eos-userutils.git"
branch = "eos-july"
rev = "4b499139daa596336e29e2148df1124f00b191ab"

[build]
template = "custom"
script = """
DYNAMIC_INIT
cookbook_cargo
cp -rv "${COOKBOOK_SOURCE}/res" "${COOKBOOK_STAGE}/etc"
ln -s id "${COOKBOOK_STAGE}/usr/bin/whoami"
"""
