[source]
# E-OS vendored mirror of redox-os/orbterm (edit freely; sync via scripts/sync-forks.sh).
git = "https://gitlab.com/e-os/eos-orbterm.git"
branch = "master"
rev = "c2a1026a0ffb24b85ab37543b9f8d228163e8353"

[build]
template = "custom"
script = """
DYNAMIC_INIT
mkdir -pv "${COOKBOOK_STAGE}/usr/share/ui"
cp -rv "${COOKBOOK_SOURCE}/apps" "${COOKBOOK_STAGE}/usr/share/ui/apps"

cookbook_cargo
"""

[package]
dependencies = [
    "orbital"
]
